Bug fixes for hrapp and acc deploy
Azure/cloud-for-sovereignty-quickstarts pull request #12
Opened 2024-02-28 16:02 UTC by azure-lm

Fixing 2 issues:
 
1. During infra deployment, the key management permissions are not applied instantly making some future operations fail with an invalid permission error. This results in many failed deployments as our retry logic won't apply when it gets a permission error. Enabling retries on permission errors.
2. Azure and SQL sessions are required to deploy the sample app. However, for some customers it seems the SQL sessions time out causing further deployment errors. Updated the code to create a valid SQL session when it's needed so the **Add-SqlAzureAuthenticationContext** setup step is not strictly needed anymore.

2024-02-28 16:55 UTC, KevinRabun approved these changes

2024-02-28 22:06 UTC, ugreg requested changes

2024-02-28 22:09 UTC, azure-lm commented on sovereignApplications/confidential/hrAppWorkload/scripts/initializeDatabase.ps1
> +    $keyVaultAccessToken = (Get-AzAccessToken -ResourceUrl https://vault.azure.net).Token
Seems to be so, code works and was pulled from here: https://learn.microsoft.com/en-us/powershell/module/sqlserver/new-sqlazurekeyvaultcolumnmasterkeysettings?view=sqlserver-ps#example-2-create-a-sqlcolumnmasterkeysettings-with-auto-signed-properties-allowing-enclave-computations

2024-02-29 03:19 UTC, ugreg approved these changes

2024-02-29 16:07 UTC, merged